services:
    postgres:
        image: 'uselagoon/postgres-14-drupal:latest'
        labels:
            lagoon.type: postgres
    cli:
        build:
            context: .
            dockerfile: lagoon/cli.dockerfile
        image: sailonlagoon
        labels:
            lagoon.type: cli-persistent
            lagoon.persistent.name: nginx
            lagoon.persistent: /app/storage
    php:
        build:
            context: .
            dockerfile: lagoon/php.dockerfile
            args:
                CLI_IMAGE: sailonlagoon
        labels:
            lagoon.type: nginx-php-persistent
            lagoon.name: nginx
            lagoon.persistent: /app/storage/
        volumes:
            - './:/app:delegated'
    nginx:
        build:
            context: .
            dockerfile: lagoon/nginx.dockerfile
            args:
                CLI_IMAGE: sailonlagoon
        labels:
            lagoon.type: nginx-php-persistent
            lagoon.name: nginx
            lagoon.persistent: /app/storage
        volumes:
            - './:/app:delegated'
        depends_on:
            - cli
